export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_PENDING = "GET_CATEGORIES_PENDING";
export const GET_CATEGORIES_FULFILLED = "GET_CATEGORIES_FULFILLED";
export const GET_CATEGORIES_REJECTED = "GET_CATEGORIES_REJECTED";

export const getCategories = () => ({
  type: GET_CATEGORIES
});

export const GET_JOKE_BY_CATEGORY = "GET_JOKE_BY_CATEGORY";
export const GET_JOKE_BY_CATEGORY_PENDING = "GET_JOKE_BY_CATEGORY_PENDING";
export const GET_JOKE_BY_CATEGORY_FULFILLED = "GET_JOKE_BY_CATEGORY_FULFILLED";
export const GET_JOKE_BY_CATEGORY_REJECTED = "GET_JOKE_BY_CATEGORY_REJECTED";

export const getJokeByCategory = category => ({
  type: GET_JOKE_BY_CATEGORY,
  payload: category
});

export const GET_RANDOM_JOKE = "GET_RANDOM_JOKE";
export const GET_RANDOM_JOKE_PENDING = "GET_RANDOM_JOKE_PENDING";
export const GET_RANDOM_JOKE_FULFILLED = "GET_RANDOM_JOKE_FULFILLED";
export const GET_RANDOM_JOKE_REJECTED = "GET_RANDOM_JOKE_REJECTED";

export const getRandomJoke = () => ({
  type: GET_RANDOM_JOKE
});
